#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('vigir_rqt_bdi_pelvis_pose')
import rospy
from vigir_rqt_bdi_pelvis_pose.pelvis_pose_qt import BDIPelvisPoseDialog

from PySide.QtCore import * 
from PySide.QtGui import *

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('vigir_rqt_bdi_pelvis_pose')

    # Initialize Qt
    app = QApplication(sys.argv)

    gui = BDIPelvisPoseDialog()
    gui.show()

    app.exec_()