#!/usr/bin/env python

import sys

import roslib

pkg = 'vigir_rqt_footstep_terrain_control'
roslib.load_manifest(pkg)

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg))
