#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('vigir_rqt_joint_control')
import rospy
from vigir_rqt_joint_control.joint_control_qt import JointControlDialog

from PySide.QtCore import * 
from PySide.QtGui import *

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('vigir_rqt_joint_control')

    # Initialize Qt
    app = QApplication(sys.argv)

    gui = JointControlDialog()
    gui.show()

    app.exec_()