#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('vigir_rqt_footstep_param_control')
import rospy
from vigir_rqt_footstep_param_control.footstep_param_control_qt import FootstepParamControlDialog

from PySide.QtCore import * 
from PySide.QtGui import *

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('vigir_rqt_footstep_param_control')

    # Initialize Qt
    app = QApplication(sys.argv)

    gui = FootstepParamControlDialog()
    gui.show()

    app.exec_()
