#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('vigir_rqt_control_mode')
import rospy
from vigir_rqt_control_mode.control_mode_qt import ControlModeDialog

from PySide.QtCore import * 
from PySide.QtGui import *

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('vigir_rqt_control_mode')

    # Initialize Qt
    app = QApplication(sys.argv)

    gui = ControlModeDialog()
    gui.show()

    app.exec_()