#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('vigir_rqt_position_mode')
import rospy
from vigir_rqt_position_mode.position_mode_qt import PositionModeDialog

from PySide.QtCore import * 
from PySide.QtGui import *

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('vigir_rqt_position_mode')

    # Initialize Qt
    app = QApplication(sys.argv)

    gui = PositionModeDialog()
    gui.show()

    app.exec_()